@startuml
!include utils/C4_Context.puml
!include utils/C4_Container.puml
!include utils/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include DEVICONS/go.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/android.puml
!include DEVICONS/redis.puml
!include DEVICONS2/react_original.puml
!include MATERIAL/router.puml
!include MATERIAL/message.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

Container_Boundary(cb, "API управления устройствами") {

    Boundary(pl_b, "ProgrammableLogicModule") {
        Component(programmableLogicAPIController, "ProgrammableLogicAPIController")
        Component(programmableLogicAddService, "ProgrammableLogicAddService")
        Component(programmableLogicEditService, "ProgrammableLogicEditService")
        Component(programmableLogicDeleteService, "ProgrammableLogicDeleteService")
        Component(logicRepository, "LogicTargetRepository")
    }

    Rel(programmableLogicAPIController, programmableLogicAddService, "uses", "")
    Rel(programmableLogicAPIController, programmableLogicEditService, "uses", "")
    Rel(programmableLogicAPIController, programmableLogicDeleteService, "uses", "")

    Rel(programmableLogicAddService, logicRepository, "uses", "")
    Rel(programmableLogicEditService, logicRepository, "uses", "")
    Rel(programmableLogicDeleteService, logicRepository, "uses", "")

    Boundary(tel_b, "TelemetryModule") {
        Component(telemetryAPIController, "TelemetryAPIController")
        Component(telemetryService, "TelemetryService")
        Component(telemetryRepository, "TelemetryRepository")
    }

    Rel(telemetryAPIController, telemetryService, "uses", "")
    Rel(telemetryService, telemetryRepository, "uses", "")

    Boundary(commands_b, "CommandsModule") {
        Component(commandsAPIController, "CommandsAPIController")
        Component(commandsService, "CommandsService")
        Component(iotGatewayClient, "IoTGatewayClient")
    }

    Rel(commandsAPIController, commandsService, "uses", "")
    Rel(commandsService, iotGatewayClient, "uses", "")
}


@enduml
