@startuml
!include utils/C4_Context.puml
!include utils/C4_Container.puml
!include utils/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

Person(user1, "Пользователь", "Клиент, управляющий умным домом", $sprite="users")
System(warehouse, "Система умного дома")
System(device, "Устройство умного дома")

Rel(user1, warehouse, "Управляет домом")
Rel(user1, warehouse, "Добавляет и настраивает устройства")
Rel(user1, warehouse, "Программирует систему")

Rel(warehouse, device, "Управляет устройством")
Rel(device, warehouse, "Получает данные с устройства")

@enduml
